server:
  port: 8001
spring:
  application:
    name: spring-redis
  redis:
    host: 192.168.1.236
    port: 7001
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity
logging:
  level:
    com:
      baizhi:
        dao: debug
